# Gunakan Node.js versi LTS
FROM node:18-alpine

# Tentukan working directory
WORKDIR /app

# Salin package.json dan package-lock.json terlebih dahulu (cache layer)
COPY package*.json ./

# Install dependency
RUN npm install

# Salin seluruh kode program
COPY . .

# Set environment variable untuk React
ENV PORT=3000
ENV CHOKIDAR_USEPOLLING=true

# Expose port React
EXPOSE 3000

# Jalankan aplikasi development
CMD ["npm", "start"]